<a href="https://colab.research.google.com/github/Sivalakshmiee/Programs/blob/main/python_programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = 2
y = 3
x + y

In [ ]:
x = x + 2

In [ ]:
x = x + 2

In [ ]:
a,b = 5,6
a
b

In [ ]:
n = 7
n
-n #unary

In [ ]:
#relational
a = 5
b = 6
a > b
a==b
a = 6
a == b
a <= b
a >= b
a != b

In [ ]:
#logical
a = 5
b = 4
a < 8 and b < 5
a < 8 or b < 2
x = False
not x

Number System Conversion


In [ ]:
bin(25)  #decimal (0-9)to binary 0,1
0b110
oct(25)
hex(25)
hex(10)
0xf
bin(31)
0b11111

In [ ]:
#swap
a = 4
b = 6

#temp = a
#a = b
#b = temp

#a = a ^ b #formula
#b = a ^ b
#a = a ^ b

a, b = b, a

print(a)
print(b)

In [ ]:
#bitwise
~12 #reverse of 12 in binary format, take 2's complement

#bitwise and
12 & 13  # convert binary do and operations

12 | 13

25 & 30

#xor
12 ^ 13

#leftshit
10 << 2

#rightshit
10 >> 2

In [ ]:
#Import math functions in python

import math as m

x = math.sqrt(25)

x

print(math.ceil(2.9)) #floor give lowest, ceil gives highest

print(math.pow(3,2))

m.sqrt(15)




In [ ]:
from math import sqrt, pow

pow(2,3)

In [ ]:
#user input in python
x = int(input("number1:"))
y = int(input("number2:"))
z = x + y
print(z)

In [ ]:
ch = eval(input('enter a expression'))
print(ch)

In [ ]:
import sys

x = sys.argv[1]
y = sys.argv[2]
z = x + y
print(z)

In [ ]:
#if else elif
x = 8
r = x % 2
if r == 0:
  print("even")
  if x > 5:
    print("greater")
  else:
    print("Less")
else:
  print("odd")


print("Bye")

In [ ]:
#if else elif

x = 5


if x == 1:
  print("1")

elif x == 2:
  print("2")

elif x == 3:
  print("3")

else:
  print("wrong input")



wrong input


In [ ]:
#while

i = 1
j = 1             #initial
while i <= 4:       #condition
  print("Good" , end="")
  while j <= 4:
    j=1
    print("day")
    j = j + 1
  i = i+1          #increment/decrement

In [ ]:
#for loop

x = "SIVALAKSHMI"
for i in x:
  print(i)

In [ ]:
#for loop
for i in [2, 4, 2.4, 1]:
  print(i)

In [ ]:
#for loop

for i in range(11, 21, 2):
  print(i)

In [ ]:
for i in range(21, 11, -1):
  print(i)

In [ ]:
for i in range(1, 21):
  if i % 5 != 0:
    print (i)

In [ ]:
#break continue pass

av = 5
x = int(input("How many cars you want?"))

i = 1
while i<=x:
  if i > av:
    print("out of stock")
    break
  print("cars")
  i += 1

In [ ]:
for  i in range(1,101):
  if i % 3 == 0 and i % 5 == 0:
    continue
  print(i)

print("get lost")

In [ ]:
for i in range(1, 101):
  if i %2 != 0:
    pass
  else:
    print(i)

In [ ]:
#pattern
for i in range(4):
  for j in range(4):
    print("# ", end="")

  print()



# # # # 
# # # # 
# # # # 
# # # # 


In [ ]:
#i rows j columns

for i in range(4):
  for j in range(4-i):
    print("# ", end="")

  print()

# # # # 
# # # 
# # 
# 


In [ ]:
#for and else together

nums = [67, 89, 91, 101]

for i in nums:

  if i % 5 == 0:
    print(i)
    break
else:
  print("Not found")

Not found


In [ ]:
#prime numbers

num = 10

for i in range(2,num):
  if num % i == 0:
    print("Not prime")
    break
else:
  print("Prime")

Not prime


In [ ]:
#arrays - the datatypes are same in array

# no fixed size

from array import *

vals = array('i', [6, 8, -5, 4])

newArr = array(vals.typecode, (a for a in vals))

#vals.reverse()

#for i in range(len(vals)):
for e in newArr:
  print(e)



6
8
-5
4


In [ ]:
from array import *

vals = array('i', [6, 3, 8, 2, 7])

newArr = array(vals.typecode, (a*a for a in vals))

i = 0

while i<len(newArr):
  print(newArr[i])
  i += 1

36
9
64
4
49


In [ ]:
#array values from user in python

from array import *
arr = array('i', []) # empty array
n = int(input("enter a array length:"))
for i in range(n):
  n = int(input("enter a array:"))
  arr.append(n)

print(arr)

val = int(input("Enter a element to search:"))

k=0
for e in arr:
  if e == val:
    print(k)
    break
  k+=1

print(arr.index(val))




In [ ]:
from numpy import * #array(), linespace(), logspace(), arange(), zeros(), ones()

arr = array([1, 2, 3, 4, 5, 6.5], int)

print(arr.dtype)
print(arr)

int64
[1 2 3 4 5 6]


In [ ]:
from numpy import *

arr = zeros(6, int)

print(arr)

[0 0 0 0 0 0]


In [ ]:
#copying array

from numpy import *

arr = array([1,2,3,4,5])

arr1 = array([11,72,33,4,5])


arr2 = arr + arr1

print(concatenate((arr,arr1)))

[ 1  2  3  4  5 11 72 33  4  5]


In [ ]:
from numpy import *

arr1 = array([1,2,3,4,5])

arr2 = array([11,72,33,4,5])

arr2 = arr1.copy() #deep copy

arr1[1] = 7 #shallow copy

print(arr1)
print(arr2)

[1 7 3 4 5]
[1 7 3 4 5]


In [ ]:
#working with matrix

from numpy import *
arr1 = array([[1,2,3,4,5,6],[4,5,6,7,8,9]])

arr2 = arr1.flatten()

arr3 = arr2.reshape(2,2,3)
print(arr3)



[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]]


In [ ]:
from numpy import *


m1 = matrix('1,2,3;4,5,6,;7,8,9')
m2 = matrix('8,2,3;3,6,6,;7,8,5')

m3 = m1 * m2

# print(m3)
# print(diagonal(m))
# print(m.max())

[[ 35  38  30]
 [ 89  86  72]
 [143 134 114]]
[1 5 9]
9


In [ ]:
# Functions in python

def siva():
  print("Good")
  print("Day")

siva()

siva()





Good
Day
Good
Day


In [ ]:
def add_sub(x, y):
  c = x + y
  d = x - y
  return c,d

result1, result2 = add_sub(7, 5)

print(result1, result2)

12 2


In [ ]:
#function arguments

def append(x):
  x = 8
  print(id(x))
  print("x",x)

a = 10
print(id(a))
append(a)
print("a",a)


135615127044624
135615127044560
x 8
a 10


In [ ]:
#types of arguments

def add_sum(x, y=12): #formal argument
  a = x + y
  b = x - y
  print(a)
  print(b)

add_sum(5, 6) #actual  (position, keyword, varible length,default)

11
-1


In [ ]:
#keyworded varible length arguments **kwargs

def person(name, **data):

  print(name)

  for i, j in data.items():
    print(i,j)
  #print(data)

person('siva', age=21, city='tvl', mob=6874327567)

siva
age 21
city tvl
mob 6874327567


In [ ]:
#global keyword

a = 4 #global
print(id(a))

def some():
  x = globals()['a']
  a = 3 #local
  print(id(a))

  print(a)
  globals()['a'] = 15 #update
some()


print(a)


135615127044432
135615127044400
3
15


In [ ]:
#pass list to a function

def count(lst):
  even = 0
  odd = 0
  for i in lst:
    if i % 2 == 0:
      even +=1
    else:
      odd+= 1
  return even, odd

lst = [23,21,22,23,2,4,25]
even, odd = count(lst)

print("Even : {} and Odd : {}".format(even,odd))




Even : 3 and Odd : 4


In [ ]:
#Fibonacci series

def fib(x):

  a = 0
  b = 1
  if x == 1:
    return 1
  else:
    print(a)
    print(b)

    for i in range(2, x):

      c = a+b
      a = b
      b = c

      print(c)


fib(5)

In [ ]:
#factorial
def fact(x):

  f = 1

  for i in range(1, x+1):
    f = f * i
  return f

x = 5
result = fact(x)
print(result)



In [ ]:
#recursion
import sys

sys.setrecursionlimit(100)
print(sys.getrecursionlimit())

i = 0
def hello():
  global i
  i += 1
  print("Hello", i)
  hello()

hello()

In [ ]:
#factorial recursion
def fact(n):

  if(n == 0):
    return 1

  return n*fact(n-1)



result = fact(3)

print(result)



6


In [ ]:
#anonymous functions

f = lambda a,b : a-b

result = f(5,6)

print(result)

-1


In [ ]:

#filter map reduce

#filter, map, reduce

from functools import reduce
num = [3,5,2,5,7,8,4,9]

evens = list(filter(lambda n : n % 2 == 0, num))         #filter from the list we give

doubles = list(map(lambda n : n + 2,evens))

sum = reduce(lambda a,b : a + b,doubles)

print(sum)

In [ ]:
#decorators

def div(a, b):
  print(a/b)

def smart(func):

  def inner(a,b):
    if a < b:
      a,b = b,a
    return func(a,b)
  return inner

div = smart(div)
div(2,4)

2.0


In [ ]:
#modules
#import calc

def add(a, b):
  return a + b

def sub(a, b):
  return a - b

def mul(a, b):
  return a * b

def div(a, b):
  return a / b


In [ ]:
#from calc import *

a = 7
b = 6

c = add(a, b)

print(c)

In [ ]:
#special varible name

print("hello",__name__)


hello __main__


#oops

Functional Programming

Procedure programming

Object oriented programming (attributes, behaviour) - Object, Encapsulation, Abstraction, Polymorphism, class

class - design (blueprint)
object - instance




In [ ]:
#class and object

class Hello:
  #atrributes - datatypes
  #behaviours - methods

  def config(self): #self - object which passing
    print("i6, 32gb")


com1 = Hello()
com2 = Hello()
Hello.config(com1)
Hello.config(com2)

com1.config()
com2.config()


i6, 32gb
i6, 32gb


In [ ]:
#__init__

class Hello:
  #atrributes - datatypes
  #behaviours - methods
  def __init__(self,cpu,ram): #called automatically
    self.cpu = cpu
    self.ram = ram


  def config(self): #self - object which passing
    print("Congig", self.cpu, self.ram)


com1 = Hello('15', '16gp') #com1 default
com2 = Hello('amd', '5')


com1.config()
com2.config()


In [ ]:
from typing_extensions import Self
#constrator, self and comparing objects

class Computer:
  def __init__(self):
    self.name = "Siva"
    self.age = 21

  # def update(self):
  #   self.age = 56

  def compare(self, other):
    if self.age == other.age:
      return True
    else:
      return False


c1 = Computer() #constractor
c2 = Computer()

c1.name = 'siva'
c1.age = 13
c2.name = 'siva2'
c2.age = 23

if c1.compare(c2):
  print("They are same")
else:
  print("different")




# print(c1.name)
# print(c2.name)

different


In [ ]:
#types of variables

#Instance variable, static variable

class Car:
  def __init__(self):
    self.name = 'bmw'
    self.model = 10

c1 = Car()
c2 = Car()

In [ ]:
#Types of methods

#instance, class, static

class Student:

  school = "Hello"

  def __init__(self,m1,m2,m3):
    self.m1 = m1
    self.m2 = m2
    self.m3 = m3

  def avg(self):
    return (self.m1 + self.m2 + self.m3) / 3

  def get_m1(self):
    return self.m1

  @classmethod
  def info(cls):
    print(cls.school)

  @staticmethod
  def info():
    print("fhrg87rguiberuyfywewgf8urfij")


#instance - accessor, mutator

s1 = Student(100,99,97)
s2 = Student(67,89,99)

print(s1.avg())
print(Student.info())


98.66666666666667
fhrg87rguiberuyfywewgf8urfij
None


In [ ]:
#inner class

class Student:

  def __init__(self, name, rollno):
    self.name = name
    self.rollno = rollno
    self.lap = self.Laptop()

  def show(self):
    print(self.name, self.rollno)
    self.lap.show()

  class Laptop:

    def __init__(self):
      self.brand = 'hp'

    def show(self):
      print(self.brand)




s1 = Student('siva', 2)

s1.show()

#lap = Student.Laptop()



siva 2
hp


In [ ]:
#inheritance

class A:
  def features1(self):
    print("feature1")

  def features2(self):
    print("feature2")

class B: #child class
  def features3(self):
    print("3")

  def features4(self):
    print("4")

class C(B):
  def features5(self):
    print("5")


a1 = A()
a2 = A()

b1 = B()


a1.features1()
a2.features2()

feature1
feature2


In [ ]:
#duck typing - polymorphism

class Google:
  def execute(self):
    print("summa")


class Laptop:


  def code(self,ide):
    ide.execute()

ide = Google()

lap1 = Laptop()
lap1.code(ide)



summa


In [ ]:
#operator overloading

#systentic sugar (int + string) error

a = 7

b= 6

print(a + b)

print(int.__sub__(a,b))



13
1


In [ ]:
class Student:

  def __init__(self,m1,m2):
    self.m1 = m1
    self.m2 = m2

  def __add__(self, other):
    m1 = self.m1 + other.m1
    m2 = self.m2 + other.m2
    s3 = Student(m1, m2)

    return s3

s1 = Student(78, 89)
s2 = Student(89, 90)

s3 = s1 + s2

print(s3.m1)

167


In [ ]:
#generator

def topten():
  n = 1

  while n <= 10:
    sq = n*n
    yield sq
    n+=1


values = topten()

for i in values:
  print(i)

In [ ]:
#error handling compile, logical, runtime

a = 5
b = 2

k = int(input("number:"))
print(k)
try:
  print(a / b)


except Exception as e:
  print(e)

finally:
  print("Resource closed")

print('bye')

number:7
7
2.5
Resource closed
bye


In [ ]:
#multithreading

from time import sleep
from threading import *

class Hello(Thread):
  def run(self):
    for i in range(5):
      print("hello")
      sleep(1)

class Hi(Thread):
  def run(self):
    for i in range(5):
      print("hi")
      sleep(1)

t1 = Hello()
t2 = Hi()

t1.start()
sleep(0.2)
t2.start()

t1.join()
t2.join()

print('bye')

hi
hello
hello
hi
hi
hello
hi
hello
hello
hi
hi
hello
hi
hello
hello
hi
hello
hi
hi
hello
hello
hi
hello
hi
hihello

hello
hi
hello
hi
hihello

bye


In [ ]:
#linear search


pos = -1
def search(list,n):

  i = 0
  while i < len(list):
    if list[i] == n:
      globals() ['pos'] = i
      return True
    i = i + 1
  return False

list = [8,5,4,9,1,4]

n = 5

if search(list, n):
  print('found',pos+1)

else:
  print("Not found")



found 2


In [ ]:
#binary search

#mid index = (lower + upper) / 2
#change the value of lower bound because of the mid is smaller than the target
# for upper bound vice versa
pos = -1
def search(list,n):
  l = 0
  u = len(list) - 1
  while l <= u:
    mid = (l + u) // 2

    if list[mid] == n:
      globals()['pos'] = mid
      return True
    else:
      if list[mid] < n:
        l = mid + 1
      else:
        u = mid - 1

  return False


list = [34,35,36,38,39,40,42]

n = 35

if search(list, n):
  print("Found",pos+1)

else:
  print("Not found")



Found 2


In [ ]:
#bubble sort

def sort(nums):
  for i in range(len(nums)-1,0,-1):
    for j in range(i):
      if nums[j] >nums[j+1]:
        temp = nums[j]
        nums[j] = nums[j + 1]
        nums[j + 1] = temp



nums = [5 ,3,8,6,7,2]
sort(nums)

print(nums)

[2, 3, 5, 6, 7, 8]


In [ ]:
#selection sort

def sort(nums):

  for i in range(5):
    minpos = i
    for j in range(i, 6):
      if nums[j] < nums[i]:
        minpos = j

    temp = nums[i]
    nums[i] = nums[minpos]
    nums[minpos] = temp


nums = [5 ,3,8,6,7,2]
sort(nums)

print(nums)

[2, 3, 5, 6, 7, 8]


In [ ]:
# car = {'brand': 'Audi', 'model': 'q7'}
# car['model'] = 'q8'
# len(car)

#No two items for same key, lastest one will be available
#dictionary are mutable

#length of the dictionary, key value pair

#dict() constructor

car = dict(brand = 'audi', model = 'q6')
car




{'brand': 'audi', 'model': 'q6'}

In [ ]:
#Accessing Dictionary items

#Access values using key names

car = {'brand': 'Audi', 'model': 'q7'}

car['brand']

#Access use get method

car.get('model')

#access use keys in keys() method

#view object containing keys as a list - any changes can reflect the dict

car_keys = car.keys()

car['fuel'] = 'petrol'

car_keys

#access values using values() method
#view object containing keys as a list - any changes can reflect the dict

car_values = car.values()

car_values

#access items in the items method

#view object containing keys as a list - any changes can reflect the dict

car_items = car.items()

car_items

car['speed'] = '190'

car_items

dict_items([('brand', 'Audi'), ('model', 'q7'), ('fuel', 'petrol'), ('speed', '190')])

In [ ]:
#changing and adding

#change values using key names

car = {'brand': 'Audi', 'model': 'q7'}

car["model"] = 'q8'

car

#change use update() method

car.update({'brand': 'TATA'})

car

#add new items use key names

car['fuel'] = 'petrol'

car

#add new items use update() method

car.update({'color': 'black'})

car

{'brand': 'TATA', 'model': 'q8', 'fuel': 'petrol', 'color': 'black'}

In [ ]:
#removing dictionary items

#remove an item using pop() method

car = {'brand': 'TATA', 'model': 'q8', 'fuel': 'petrol', 'color': 'black'}

car.pop('model')

car

car.popitem() #return as a tuple

car

#using del keyword

del car['fuel'] # does not return anything

car

#remove dict using del keyword

del car

#clear() method

car = {'brand': 'TATA', 'model': 'q8', 'fuel': 'petrol', 'color': 'black'}

car.clear() #dict not delete it's clear

car

{}

In [ ]:
#copying a dictionary

#assignment operator cannot be used to copy immutable objects

car = {'brand': 'TATA', 'model': 'q8', 'fuel': 'petrol', 'color': 'black'}


car_copy = car

car_copy['model'] = 'i10'

car_copy

#using copy()

car_copy1 = car.copy()

car_copy1['brand'] = "lamborgini"

car_copy1

#using dict()

car_copy2 = dict(car)

car_copy2['model'] = 'yu7'

car_copy2

car



{'brand': 'TATA', 'model': 'i10', 'fuel': 'petrol', 'color': 'black'}

In [ ]:
#map

A, B = map(int, input().split())